version: '3.9'
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    volumes:
      - postgres_db:/bitnami/postgresql
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami
  airflow-worker:
    image: bitnami/airflow-worker:latest
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=false
    depends_on:
      - airflow
    restart: always
    
  airflow-scheduler:
    build:
      context: ./
      dockerfile: ./airflow-scheduler.dockerfile
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=false
    depends_on:
      - airflow
    restart: always
  airflow:
    image: bitnami/airflow:latest
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_USERNAME=user
      - AIRFLOW_EMAIL=user@example.com
    ports:
      - '8080:8080'
    restart: always

volumes:
  postgres_db:
    driver: local
  redis_data:
    driver: local





# version: '3.9'
# # docker exec -it -u root 7e74e9c80a80  /bin/bash
# services:
#   postgresql:
#     image: docker.io/bitnami/postgresql:15
#     volumes:
#       - 'postgresql_data:/bitnami/postgresql'
#     environment:
#       - POSTGRESQL_DATABASE=bitnami_airflow
#       - POSTGRESQL_USERNAME=bn_airflow
#       - POSTGRESQL_PASSWORD=bitnami1
#       # ALLOW_EMPTY_PASSWORD is recommended only for development.
#       - ALLOW_EMPTY_PASSWORD=yes
#     restart: always
#   redis:
#     image: docker.io/bitnami/redis:7.0
#     volumes:
#       - 'redis_data:/bitnami'
#     environment:
#       # ALLOW_EMPTY_PASSWORD is recommended only for development.
#       - ALLOW_EMPTY_PASSWORD=yes
#     restart: always
#   airflow-scheduler:
#     image: docker.io/bitnami/airflow-scheduler:latest
#     volumes:
#       - ./dags:/opt/bitnami/airflow/dags
#     environment:
#       - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
#       - AIRFLOW_DATABASE_NAME=bitnami_airflow
#       - AIRFLOW_DATABASE_USERNAME=bn_airflow
#       - AIRFLOW_DATABASE_PASSWORD=bitnami1
#       - AIRFLOW_EXECUTOR=CeleryExecutor
#       - AIRFLOW_WEBSERVER_HOST=airflow
#       - AIRFLOW_LOAD_EXAMPLES=false
#     restart: always
#   airflow-worker:
#     image: docker.io/bitnami/airflow-worker:latest
#     volumes:
#       - ./dags:/opt/bitnami/airflow/dags
#     environment:
#       - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
#       - AIRFLOW_DATABASE_NAME=bitnami_airflow
#       - AIRFLOW_DATABASE_USERNAME=bn_airflow
#       - AIRFLOW_DATABASE_PASSWORD=bitnami1
#       - AIRFLOW_EXECUTOR=CeleryExecutor
#       - AIRFLOW_WEBSERVER_HOST=airflow
#     restart: always
#   airflow:
#     image: docker.io/bitnami/airflow:latest
#     volumes:
#       - ./dags:/opt/bitnami/airflow/dags
#     environment:
#       # username: user
#       # password: bitname
#       - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
#       - AIRFLOW_DATABASE_NAME=bitnami_airflow
#       - AIRFLOW_DATABASE_USERNAME=bn_airflow
#       - AIRFLOW_DATABASE_PASSWORD=bitnami1
#       - AIRFLOW_EXECUTOR=CeleryExecutor
#     restart: always
#     ports:
#       - '8080:8080'
# volumes:
#   postgresql_data:
#     driver: local
#   redis_data:
#     driver: local
